# Generated by Django 3.1.5 on 2021-06-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=10000)),
                ('awnser', models.CharField(max_length=100)),
                ('diagram', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Diagrams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='challenge',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
