# Generated by Django 3.1.5 on 2021-06-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0002_auto_20210605_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('admin', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='challenges',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='diagrams',
            old_name='name',
            new_name='type',
        ),
        migrations.AddField(
            model_name='challenges',
            name='diagram_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gymkhana.diagrams'),
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('challenges', models.ManyToManyField(to='gymkhana.Challenges')),
                ('creator', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gymkhana.users')),
            ],
        ),
        migrations.AddField(
            model_name='challenges',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gymkhana.users'),
        ),
    ]
