# Generated by Django 3.2 on 2021-10-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0003_auto_20210615_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
