# Generated by Django 3.2 on 2021-11-17 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0004_users_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='challenges',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenges',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='challenges_passed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymkhana.challenges'),
        ),
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
