# Generated by Django 3.2 on 2022-04-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0008_rename_imagen_challenges_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagrams',
            old_name='diagram_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='games',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='challenges_passed',
        ),
        migrations.AddField(
            model_name='users',
            name='challenges_passed',
            field=models.ManyToManyField(blank=True, to='gymkhana.Challenges'),
        ),
    ]
