# Generated by Django 3.2 on 2022-04-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0009_auto_20220413_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='diagram',
        ),
    ]
