# Generated by Django 3.2 on 2022-05-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0010_remove_challenges_diagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='gymkhana.users'),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='diagram_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='gymkhana.diagrams'),
        ),
        migrations.AlterField(
            model_name='games',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='gymkhana.users'),
        ),
    ]
